// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.
import Auth from '@aws-amplify/auth';
const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:6260a963-cecb-4f0f-85f2-8d54182305d9',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_on4bPYWw1',
  aws_user_pools_web_client_id: '6sgecljord9rn6sm9bon55642n',
  oauth: {},
};

export default awsmobile;
